config/routes.rb
Rails.application.routes.draw do

  root    'sessions#new'  
  
  get     '/home',              to: 'static_pages#home'       #home_path
  get     '/login',             to: 'sessions#new'            #login_path
  post    '/login',             to: 'sessions#create'
  delete  '/logout',            to: 'sessions#destroy'
  get     '/edit_connections',  to: 'users#edit_connections'
  
  resources :users do
    member do
      get :search
      get :edit_connections
      patch :update_connections
      put :update_connections
      get :courses
      get :groups
      get :skills
      get :clients
      end
  end
  
  resources :courses do
    member do
      get :users
    end
  end
  
  resources :groups do
    member do
      get :users
    end
  end
  
  resources :skills do
    member do
      get :users
    end
  end
  
  resources :clients do
    member do
      get :users
    end
  end
  
  resources :microposts,          only: [:create, :destroy]
  resources :user_courses,        only: [:create, :destroy]
  resources :user_groups,         only: [:create, :destroy]
  resources :user_skills,         only: [:create, :destroy]
  resources :user_clients,        only: [:create, :destroy]
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :user_groups, foreign_key: "group_id", dependent: :destroy
  has_many :users, through: :user_groups
  
  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  
  validates :attitude, presence: true, length: { maximum: 10 }
  validates :name, presence: true, length: { maximum: 100 }, uniqueness: { case_sensitive: false }
  validates :email, presence: true, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :contact, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 1000 }
  
  # Searches in name and description
  def self.search(search)
    search = search.downcase
    wildcard_search = "%#{search}%"
    where("lower(attitude) LIKE ? OR " +
          "lower(name) LIKE ? OR " +
          "lower(email) LIKE ? OR " +
          "lower(contact) LIKE ? OR " +
          "lower(description) LIKE ?", 
          wildcard_search, wildcard_search, 
          wildcard_search, wildcard_search,
          wildcard_search)
  end
  
  #Users
    # Connects Group to User.
    def connectToUser(connecting_user)
      user_groups.create(user_id: connecting_user.id)
    end
  
    # Disconnects Group to User.
    def disconnectFromUser(connected_user)
      user_groups.find_by(user_id: connected_user.id).destroy
    end
    
    # Returns true if the Group is connected to the User.
    def connectedToUser?(random_user)
      users.include?(random_user)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :show, :index, :edit, :update, :destroy]
  before_action :admin_user,     only: [:destroy]
  
  def new
    @group = Group.new
  end
  
  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:success] = "Nieuwe groep aangemaakt!"
      redirect_to @group
    else
      render 'new'
    end
  end
  
  def show
    @group = Group.find(params[:id])
  end
  
  def index
    @groups = Group.all
    if params[:search]
      @groups = Group.search(params[:search]).paginate(page: params[:page], per_page: 10).order("name ASC")
    else
      @groups = @groups.paginate(page: params[:page], per_page: 10).order("name ASC")
    end
  end
  
  def edit
    @group = Group.find(params[:id])
  end
  
  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params) 
      flash[:success] = "Groep succesvol bijgewerkt."
      redirect_to @group
    else
      render 'edit'
    end
  end
  
  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:error] = "Groep succesvol verwijderd."
    redirect_to groups_url
  end
  
  private

    def group_params
      params.require(:group).permit(:attitude, :name, :email, :contact, :description)
    end
end

app/views/groups/_group.html.erb
<!-- DESKTOP Groepoverzichtitem -->
<div class="ui segments listoverview">
  <div class="ui segment" id="topcontainersingleitem">
    
    <%= link_to group do %>
      <div class="<%= attitude_class(group.attitude) %>">
        <%= group.name %>
      </div>
    <% end %>
    
    <div class="overzichtdescription">
      <%= truncate(group.description, :length => description_length_index_pages) %>
    </div>    
    <div class="extra">
      <div class="ui right floated labeled button" tabindex="0"> 
      
        <% if group.users.include?(current_user) %>
          <a>
            <div class="ui red image label" id="disconnect_group_modal_<%= group.id %>">
              <i class="pencil icon"></i>
              Disconnect 
            </div>
          </a>
        <% else %>
          <a>
            <div class="ui green image label" id="connect_group_modal_<%= group.id %>">
              <i class="pencil icon"></i>
              Connect
            </div>
          </a>
        <% end %>
        
      </div>
      <%= link_to User.find_by_name(group.contact) do %>
      <div class="ui yellow image label">
        <%= image_tag(user_avatar_class(group.contact)) %>
        <%= group.contact %> 
        <div class="detail">Contactpersoon</div>
      </div>
      <% end %>
    </div>
  </div>
  <div class="ui bottom attached label">
    <i class="user icon"></i><%= group.users.count %> &nbsp; &nbsp; &nbsp;
    <i class="mail outline icon"></i><%= group.email %>
  </div> 
</div>
<!-- DESKTOP EIND Groepoverzichtitem -->

<% if group.users.include?(current_user) %>
<!-- DESKTOP Groepoverzichtitem disconnect modal-->
  <div class="ui small modal" id="disconnect_group_modal_<%= group.id %>">
    <div class="header">
      Disconnect met groep '<%= group.name %>'
    </div>
    
   
      <div class="content">
        <%= form_for(group.user_groups.find_by(user_id: current_user.id), html: { method: :delete }) do |f| %>
          <p>Weet je het zeker?</p>
          <div class="actions">
            <div class="ui black deny button">
              Annuleren
            </div>
            <%= f.button( :class => 'ui negative right labeled icon button' ) do %>
              Disconnect <i class="remove icon"></i>
            <% end %>
          </div>
        <% end %>
      </div>
      
  </div>
<!-- DESKTOP EIND Groepoverzichtitem eind disconnect modal -->
<% else %>
<!-- DESKTOP Groepoverzichtitem eind connect modal -->
  <div class="ui small modal" id="connect_group_modal_<%= group.id %>">
    <div class="header">
      Connect met groep '<%= group.name %>'
    </div>
    
      <div class="content">
        <%= form_for(group.user_groups.build, html: {class: "ui form"}) do |f| %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
          <%= f.hidden_field :group_id %>
          <div class="actions">
            <div class="ui black deny button">
              Annuleren
            </div>
              <%= f.button( :class => 'ui positive right labeled icon button' ) do %>
                Connect <i class="checkmark icon"></i>
              <% end %>
          </div>
        <% end %>
      </div>

  </div>
<!-- DESKTOP EIND Groepoverzichtitem eind connect modal -->
<% end %>

<script>
  $(function() {
    $('div.label#connect_group_modal_<%= group.id %>').click( function(){
       $('div.modal#connect_group_modal_<%= group.id %>').modal('show');
    })
  })
  $(function() {
    $('div.label#disconnect_group_modal_<%= group.id %>').click( function(){
       $('div.modal#disconnect_group_modal_<%= group.id %>').modal('show');
    })
  })
</script>

app/views/groups/_group_form.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="fields">
  <div class="six wide required field">
    <%= f.label :name, "Naam" %>
    <%= f.text_field :name %>
  </div>
  <div class="three wide required field">
    <%= f.label :attitude, "Attitude" %>
    <%= f.select(:attitude, ['Business', 'Test', 'Technical'], 
    {prompt: default_select_value}) %>
  </div>
</div>

<div class="fields">
  <div class="four wide required field">
    <%= f.label :email, "Emailadres"  %>
    <%= f.text_field :email %>
  </div>
  <div class="six wide required field">
    <%= f.label :contact, "Contactpersoon"  %>
    <%= f.select(:contact, User.where.not(name: ['KZA Connected']).order('name asc').pluck(:name), 
    {prompt: default_select_value}) %>  
  </div>
</div>

<div class="fields">
  <div class="sixteen wide required field">
    <%= f.label :description, "Beschrijving"  %>
    <%= f.text_area :description, rows: description_rows_new_and_edit_pages %>
  </div>
</div>

app/views/groups/edit.html.erb
<% provide(:title, "Groep bewerken") %>

  <div class="ui basic segment">
          
    <div id="desktoppagetitleandsearchbar">
      <div id="titlebarsegment" class="ui basic segment">
          <h3>Groep bewerken</h3>
      </div>
    </div>
  
    <%= form_for(@group, html: {class: "ui form"}) do |f| %>
      <%= render :partial => "group_form", :locals => { :f => f } %>
      <%= f.submit "Sla wijzigingen op", class: "ui fluid large pink submit button" %>
    <% end %>

  </div>

app/views/groups/index.html.erb
<% provide(:title, "Groepen") %>
  
  <div id="desktoppagetitleandsearchbar">
    <div id="titlebarsegment" class="ui basic segment">
      <div class="ui basic left floated segment">
        <h3>Groepen</h3>
      </div>
      <div id="searchbarfix" class="ui basic right floated segment">
        <div class="ui icon input">
          <%= form_tag(groups_path, :method => "get") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Zoeken..." %>
          <%end%>
          <i class="search icon"></i>
        </div>
      </div>
    </div>
  </div>  
  
  <div class="ui basic segment">
    <div id="desktopcourseoverview">
      <% if @groups.present? %>
        <%= render @groups %>
      <% else %>
        <div class="ui basic segment">
          Geen groepen gevonden.
        </div>
      <% end %>
    </div>
    <br>
    <center><%= will_paginate %></center>
  </div>

app/views/groups/new.html.erb
<% provide(:title, "Groep aanmaken") %>

  <div class="ui basic segment">
          
    <div id="desktoppagetitleandsearchbar">
      <div id="titlebarsegment" class="ui basic segment">
          <h3>Groep aanmaken</h3>
      </div>
    </div>

    <%= form_for(@group, html: {class: "ui form"}) do |f| %>
      <%= render :partial => "group_form", :locals => { :f => f } %>
      <%= f.submit "Maak groep aan", class: "ui fluid large pink submit button" %>
    <% end %>

  </div>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>

<div class="ui basic segment">
  
  <div id="desktoppagetitleandsearchbar">
    <div id="titlebarsegment" class="ui basic segment">
        <h3>Groepsinformatie</h3>
    </div>
  </div>

  <div class="ui center aligned container">
    <div class="ui center aligned stacked segment">
      <div class="ui celled grid">
        
        <div class="row">
          <div class="six wide column">
            <h4 class="ui horizontal divider header profileheader">
              <i class="mini users icon"></i>
              Algemeen
            </h4>
            <p>
              <div class="ui grid">
                <div class="one columnn row">
                  <div class="left aligned column">
            <strong><%= label_tag 'name', 'Naam' %></strong>
                    <%= label_tag 'name', @group.name%><br>
            <strong><%= label_tag 'attitude', 'Attitude' %></strong>
                    <%= label_tag 'attitude', @group.attitude%><br>
            <strong><%= label_tag 'contact', 'Contactpersoon' %></strong>
                    <%= label_tag 'contact', @group.contact%><br>
            <strong><%= label_tag 'email', 'Emailadres' %></strong>
                    <%= label_tag 'email', @group.email%><br>
                    <br>
                    <%= link_to "Groep bewerken", edit_group_path %><br>
                    <% if current_user.admin? %>
                    <%= link_to "Groep verwijderen", @group, method: :delete, data: { confirm: "Weet je het zeker?" } %><br>
                    <% end %>
                    <br>
                  </div>
                </div>
              </div>     
            </p>
          </div>
          <div class="ten wide column">
            <h4 class="ui horizontal divider header profileheader">
              <i class="mini info icon"></i>
              Aanvullende informatie
            </h4>
            <p>
              <div class="ui grid">
                <div class="one columnn row">
                  <div class="left aligned column">
                    <p>
                      <%= h(@group.description).gsub(/\n/, '<br/>').html_safe %>
                    </p>
                  </div>
                </div>
              </div>     
            </p>
          </div>
        </div>

        <div class="one column row">
          <div class="column">
            <h4 class="ui horizontal divider header profileheader">
              <i class="mini user icon"></i>
              Collega's verbonden aan deze groep
            </h4>
            <% if @group.users.any? %>
              <div class="ui large horizontal divided list">
                <% @group.users.each do |user| %>
                  <div class="item">
                    <%= image_tag(user_avatar_class(user.name), {class: 'ui avatar image'}) %>
                    <div class="content">
                      <%= link_to(user.name, user_path(user), html: {class: 'header'}) %>
                    </div>
                  </div>
                <% end %>
              </div>
            <% else %>
              <div class="ui basic segment">
                Nog geen collega's verbonden aan deze groep.
              </div>
            <% end %>
          </div>
        </div> 
        
      </div>
    </div>
  </div>
</div>