config/routes.rb
Rails.application.routes.draw do

  root    'sessions#new'  
  
  get     '/home',              to: 'static_pages#home'       #home_path
  get     '/login',             to: 'sessions#new'            #login_path
  post    '/login',             to: 'sessions#create'
  delete  '/logout',            to: 'sessions#destroy'
  get     '/edit_connections',  to: 'users#edit_connections'
  
  resources :users do
    member do
      get :search
      get :edit_connections
      patch :update_connections
      put :update_connections
      get :courses
      get :groups
      get :skills
      get :clients
      end
  end
  
  resources :courses do
    member do
      get :users
    end
  end
  
  resources :groups do
    member do
      get :users
    end
  end
  
  resources :skills do
    member do
      get :users
    end
  end
  
  resources :clients do
    member do
      get :users
    end
  end
  
  resources :microposts,          only: [:create, :destroy]
  resources :user_courses,        only: [:create, :destroy]
  resources :user_groups,         only: [:create, :destroy]
  resources :user_skills,         only: [:create, :destroy]
  resources :user_clients,        only: [:create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :user_clients, foreign_key: "user_id", dependent: :destroy, inverse_of: :user
  has_many :user_groups, foreign_key: "user_id", dependent: :destroy, inverse_of: :user
  has_many :user_skills, foreign_key: "user_id", dependent: :destroy, inverse_of: :user
  has_many :user_courses, foreign_key: "user_id", dependent: :destroy, inverse_of: :user
  has_many :clients, through: :user_clients
  has_many :groups, through: :user_groups
  has_many :skills, through: :user_skills
  has_many :courses, through: :user_courses
  accepts_nested_attributes_for :user_courses, allow_destroy: true
  accepts_nested_attributes_for :user_groups, allow_destroy: true
  accepts_nested_attributes_for :user_skills, allow_destroy: true
  accepts_nested_attributes_for :user_clients, allow_destroy: true
  attr_accessor :remember_token
  
  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  has_secure_password
    
  validates :attitude, presence: true, length: { maximum: 10 }
  validates :name, presence: true, length: { maximum: 100 }
  validates :gender, presence: true
  validates :residence, presence: true, length: { maximum: 100 }
  validates :dateofbirth, presence: true
  validates :email, presence: true, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :phonenumber, presence: true, length: { minimum: 10, maximum: 10 }
  validates :function_level, presence: true, length: { minimum: 1, maximum: 1 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :startdate, presence: true
  validates :password, presence: true, length: { minimum: 6, maximum: 100 }, allow_nil: true 


    
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # Defines a proto-feed.
  # See "Following users" for the full implementation.
  def feed
    Micropost.limit(10)
  end
  
  # Searches in name and email
  def self.search(search)
    search = search.downcase
    wildcard_search = "%#{search}%"
    where(  "lower(attitude) LIKE ? OR " +
            "lower(name) LIKE ? OR " +
            "lower(gender) LIKE ? OR " +
            "lower(residence) LIKE ? OR " +
            "lower(phonenumber) LIKE ? OR " +
            "lower(email) LIKE ? OR " +
            "lower(description) LIKE ?", 
            wildcard_search, wildcard_search, 
            wildcard_search, wildcard_search,
            wildcard_search, wildcard_search,
            wildcard_search)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,          only: [:show, :index, :edit, :update, :destroy]
  before_action :correct_user,            only: [:edit, :update]
  before_action :set_select_collections,  only: [:update]
  before_action :admin_user,              only: [:new, :create, :destroy]

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] =  "Gebruiker '" + @user.name + "' aangemaakt!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page], per_page: 10)
    @userage = age(@user.dateofbirth).to_s
  end
  
  def index
    @users = User.where.not(name: ['KZA Connected', current_user.name]) 
    if params[:search].present?
      @users = User.search(params[:search]).paginate(page: params[:page], per_page: 10).order("name ASC")
    else
      @users = @users.paginate(page: params[:page], per_page: 10).order("name ASC")
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def edit_connections
    @user = User.find(params[:id])
  end
  
  def update
    if @user.update_attributes(user_params) 
      flash[:success] = "Profiel succesvol bijgewerkt."
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def edit_connections
    @user = User.find(params[:id])
  end
  
  def update_connections
    if @user.update_attributes(user_params) 
      flash[:success] = "Connecties succesvol bijgewerkt."
      redirect_to @user
    else
      render 'edit_connections'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:error] = "Account succesvol verwijderd."
    redirect_to users_url
  end
  
  private
    def age(dob)
      now = Time.now.utc.to_date
      now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
    end
  
    def user_params
      params.require(:user).permit(:attitude, :name, :gender, :residence, :dateofbirth, :email, :phonenumber, :function_level, :startdate, :password, :password_confirmation, :bu_manager, :is_bu_manager, :description,
                                    user_courses_attributes: [:id, :user_id, :course_id, :status, :_destroy],
                                    user_groups_attributes: [:id, :user_id, :group_id, :_destroy],
                                    user_skills_attributes: [:id, :user_id, :skill_id, :level, :_destroy],
                                    user_clients_attributes: [:id, :user_id, :from_date, :to_date, :client_id, :_destroy])
    end
end

app/views/users/_edit_connections.html.erb
<%= f.fields_for(:user_groups) do |ff| %>
  <div class="fields">
    <div class="six wide field">
      <% if ff.index == 0 %>
        <%= f.label :user_groups, "Groep"  %>
      <% end %>
      <%= ff.hidden_field :user_id %>
      <%= ff.collection_select(:group_id, Group.all, :id, :name, {prompt: default_select_value} )%>
    </div>
  </div>
<% end %><br>

<%= f.fields_for(:user_courses) do |ff| %>
  <div class="fields">
    <div class="six wide field">
      <% if ff.index == 0 %>
        <%= f.label :user_courses, "Cursus"  %>
      <% end %>
      <%= ff.hidden_field :user_id %>
      <%= ff.collection_select(:course_id, Course.all, :id, :name, {prompt: default_select_value} )%>
    </div>
    <div class="four wide field">
      <% if ff.index == 0 %>
        <%= f.label :user_courses, "Status"  %>
      <% end %>
      <%= ff.select(:status, ['Geinteresseerd', 'Ingeschreven', 'Afgerond'], {prompt: default_select_value}, label: false) %>
    </div>
  </div>
<% end %><br>

<%= f.fields_for(:user_skills) do |ff| %>
  <div class="fields">
    <div class="six wide field">
      <% if ff.index == 0 %>
        <%= f.label :user_skills, "Kennisgebied"  %>
      <% end %>
      <%= ff.hidden_field :user_id %>
      <%= ff.collection_select(:skill_id, Skill.all, :id, :name, {prompt: default_select_value} )%>
    </div>
    <div class="four wide field">
      <% if ff.index == 0 %>
        <%= f.label :user_skills, "Niveau"  %>
      <% end %>
      <%= ff.select(:level, ['Beginner', 'Gevorderd', 'Expert'], {prompt: default_select_value} ) %>
    </div>
  </div>
<% end %><br>

<%= f.fields_for(:user_clients) do |ff| %>
  <div class="fields">
    <div class="six wide field">
      <% if ff.index == 0 %>
        <%= f.label :user_clients, "Klant"  %>
      <% end %>
      <%= ff.hidden_field :user_id %>
      <%= ff.collection_select(:client_id, Client.all, :id, :name, {prompt: default_select_value} )%>
    </div>
    <div class="four wide field">
      <% if ff.index == 0 %>
        <%= f.label :user_clients, "Van"  %>
      <% end %>
      <%= ff.date_field :from_date %>
    </div>
    <div class="four wide field">
      <% if ff.index == 0 %>
        <%= f.label :user_clients, "Tot"  %>
      <% end %>
      <%= ff.date_field :to_date %>
    </div>
  </div>
<% end %><br>

app/views/users/_user.html.erb
<!-- Dit is een item van een overview list -->
<div class="ui segments listoverview">
  <div class="ui segment" id="topcontainersingleitem">
      
    <%= link_to user do %>
      <div class="<%= attitude_class(user.attitude) %>">
        <%= user.name %>
      </div>
    <% end %>
  
    <div class="overzichtdescription">
      <div class="overzichtimage">
        <%= image_tag(user_avatar_class(user.name), width: '75') %>
      </div>
      <div class="overzichttekst">
        <%= truncate(user.description, :length => description_length_index_pages) %>
      </div>
    </div>    
  
    <div class="extra">
      <% if user.user_clients.where("from_date <= ? AND to_date >= ?", DateTime.now, DateTime.now).empty? %>  
        <a class="ui yellow image label">
          <img src="">
            Niet op opdracht.
          <div class="detail">Klant</div>
        </a>
      <% else %>
      <%= link_to Client.find_by_name(user.user_clients.where("from_date <= ? AND to_date >= ?", DateTime.now, DateTime.now).first.client.name) do %>
        <div class="ui yellow image label">
          <img src="http://logo.clearbit.com/<%= user.user_clients.where("from_date <= ? AND to_date >= ?", DateTime.now, DateTime.now).first.client.name.gsub(/\s+/, "") %>.nl">
            <%= user.user_clients.where("from_date <= ? AND to_date >= ?", DateTime.now, DateTime.now).first.client.name %>
          <div class="detail">Klant</div>
        </div>
        <% end %>
      <% end %>
    </div>

  </div>
  
  <div class="ui bottom attached label">
    <% if user.gender == 'Man' %>
        <i class="male icon"></i><%= user.gender %>
    <% else %>
        <i class="female icon"></i><%= user.gender %>
    <% end %> &nbsp; &nbsp; &nbsp;
    
    <i class="location arrow icon"></i><%= user.residence %> &nbsp; &nbsp; &nbsp;
    <i class="mail outline icon"></i><%= user.email %> &nbsp; &nbsp; &nbsp;
    <i class="call icon"></i><%= user.phonenumber %> 
  </div>

</div>
<!-- Einde listitem -->

app/views/users/_user_form.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="fields">
  <div class="six wide required field">
    <%= f.label :name, "Naam" %>
    <%= f.text_field :name %>
  </div>
  <div class="three wide required field">
    <%= f.label :attitude, "Attitude" %>
    <%= f.select(:attitude, ['Business', 'Test', 'Technical'], 
    {prompt: default_select_value}) %>
  </div>
</div>

<div class="inline fields">
  <%= f.label :gender, "Geslacht" %>
  <div class="field">
    <%= f.radio_button :gender, "Man" %>
    <%= f.label :gender, "Man", :value => "Man"  %>
  </div>
  <div class="field">
    <%= f.radio_button :gender, "Vrouw" %>
    <%= f.label :gender, "Vrouw", :value => "Vrouw" %>
  </div>
</div>
  
<div class="fields">
  <div class="four wide required field">
    <%= f.label :dateofbirth, "Geboortedatum"  %>
    <%= f.date_field :dateofbirth %>
  </div>
  <div class="four wide required field">
    <%= f.label :residence, "Woonplaats"  %>
    <%= f.text_field :residence %>
  </div>
  <div class="four wide required field">
    <%= f.label :email, "Email adres"  %>
    <%= f.email_field :email %>
  </div>
    <div class="four wide required field">
    <%= f.label :phonenumber, "Telefoonnummer"  %>
    <%= f.telephone_field :phonenumber %>
  </div>
</div>

<div class="fields">
  <div class="three wide required field">
    <%= f.label :startdate, "In diensttreding datum"  %>
    <%= f.date_field :startdate %>
  </div>
  <div class="three wide required field">
    <%= f.label :function_level, "Functieniveau"  %>
    <%= f.select(:function_level, ['T','1','2','3'],
    {prompt: default_select_value}) %>
  </div>
  <div class="six wide required field">
    <%= f.label :bu_manager, "Business unit manager (Indien volgende 'Nee')"  %>
    <%= f.select(:bu_manager, User.where(:is_bu_manager => true).order('name asc').pluck(:name),
    {prompt: default_select_value}) %>
  </div>
</div>

<div class="inline fields">
  <%= f.label :is_bu_manager, "Business unit manager" %>
  <div class="field">
    <%= f.radio_button :is_bu_manager, "false" %>
    <%= f.label :is_bu_manager, "Nee", :value => false  %>
  </div>
  <div class="field">
    <%= f.radio_button :is_bu_manager, "true" %>
    <%= f.label :is_bu_manager, "Ja", :value => true %>
  </div>
</div>

<div class="fields">
  <div class="sixteen wide required field">
    <%= f.label :description, "Beschrijving"  %>
    <%= f.text_area :description, rows: description_rows_new_and_edit_pages %>
  </div>
</div>

<div class="fields">
  <div class="four wide field">
    <%= f.label :password, "Wachtwoord"  %>
    <%= f.password_field :password %>
  </div>
  <div class="four wide field">
    <%= f.label :password_confirmation, "Wachtwoord bevestiging" %>
    <%= f.password_field :password_confirmation %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Profiel bewerken") %>

  <div class="ui basic segment">
          
    <div id="desktoppagetitleandsearchbar">
      <div id="titlebarsegment" class="ui basic segment">
          <h3>Profiel bewerken</h3>
      </div>
    </div>
  
    <%= form_for(@user, html: {class: "ui form"}) do |f| %>
      <%= render :partial => "user_form", :locals => { :f => f } %>
      <%= f.submit "Sla wijzigingen op", class: "ui fluid large pink submit button" %>
    <% end %>

  </div>

app/views/users/edit_connections.html.erb
<% provide(:title, "Connecties bewerken") %>

  <div class="ui basic segment">
          
    <div id="desktoppagetitleandsearchbar">
      <div id="titlebarsegment" class="ui basic segment">
          <h3>Connecties bewerken</h3>
      </div>
    </div>
  
    <% if @user.clients.present? || @user.courses.present? || @user.skills.present? || @user.groups.present? %>
      
      <%= form_for(@user, html: {class: "ui form"}) do |f| %>
        <%= render :partial => "edit_connections", :locals => { :f => f } %>
        <%= f.submit "Sla wijzigingen op", class: "ui fluid large pink submit button" %>
      <% end %>
    
    <% else %>
      <div class="ui basic segment">
        Nog geen connecties.
      </div>
    <% end %>

  </div>

app/views/users/index.html.erb
<% provide(:title, "Collega's") %>
  
  <div id="desktoppagetitleandsearchbar">
    <div id="titlebarsegment" class="ui basic segment">
      <div class="ui basic left floated segment">
        <h3>Collega's</h3>
      </div>
      <div id="searchbarfix" class="ui basic right floated segment">
        <div class="ui icon input">
          <%= form_tag(users_path, :method => "get") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Zoeken..." %>
          <%end%>
          <i class="search icon"></i>
        </div>
      </div>
    </div>
  </div>  
  
  <div class="ui basic segment">
    <div id="desktopcourseoverview">
      <% if @users.present? %>
        <%= render @users %>
      <% else %>
        <div class="ui basic segment">
          Geen collega's gevonden.
        </div>
      <% end %>
    </div>
    <br>
    <center><%= will_paginate %></center>
  </div>

app/views/users/new.html.erb
<% provide(:title, "Gebruiker aanmaken") %>

  <div class="ui basic segment">
          
    <div id="desktoppagetitleandsearchbar">
      <div id="titlebarsegment" class="ui basic segment">
          <h3>Gebruiker aanmaken</h3>
      </div>
    </div>

    <%= form_for(@user, html: {class: "ui form"}) do |f| %>
      <%= render :partial => "user_form", :locals => { :f => f } %>
      <%= f.submit "Maak gebruiker aan", class: "ui fluid large pink submit button" %>
    <% end %>

  </div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="ui basic segment">
  
  <div id="desktoppagetitleandsearchbar">
    <div id="titlebarsegment" class="ui basic segment">
        <h3>Gebruikersprofiel</h3>
    </div>
  </div>

  <div class="ui center aligned container">
    <div class="ui center aligned stacked segment">
      <div class="ui celled grid">
        
        <div class="row">
          <div class="six wide column">
            <h4 class="ui horizontal divider header profileheader">
              <i class="mini user icon"></i>
              Algemeen
            </h4>
            <p>
              <div class="ui grid">
                <div class="one columnn row">
                  <div class="left aligned column">
                    <%= image_tag(user_avatar_class(@user.name), class: 'ui centered circular image', width: '128') %>
                    <br>
            <strong><%= label_tag 'naam', 'Naam' %></strong>
                    <%= label_tag 'naam', @user.name%><br>
            <strong><%= label_tag 'attitude', 'Attitude' %></strong>
                    <%= label_tag 'attitude', @user.attitude %><br> 
            <strong><%= label_tag 'geslacht', 'Geslacht' %></strong> 
                    <%= label_tag 'geslacht', @user.gender %><br>
            <strong><%= label_tag 'leeftijd', 'Leeftijd' %></strong>
                    <%= label_tag 'leeftijd', @userage +' jaar' %><br>
            <strong><%= label_tag 'woonplaats', 'Woonplaats' %></strong>
                    <%= label_tag 'woonplaats', @user.residence %><br>
            <strong><%= label_tag 'functieniveau', 'Functieniveau' %></strong>
                    <%= label_tag 'functieniveau', @user.function_level %><br>
            <strong><%= label_tag 'bijkzasinds', 'Bij KZA sinds' %></strong>
                    <%= label_tag 'bijkzasinds', @user.startdate.strftime("%d/%m/%Y") %><br>
            <strong><%= label_tag 'emailadres', 'Emailadres' %></strong>
                    <%= label_tag 'emailadres', @user.email%><br>
            <strong><%= label_tag 'telefoonnummer', 'Telefoonnummer' %></strong>
                    <%= label_tag 'telefoonnummer', @user.phonenumber%><br>
                    
                    <% if current_user.admin? && !current_user?(@user) %>
                      <br>
                      <%= link_to "Collega verwijderen", @user, method: :delete, data: { confirm: "Weet je het zeker?" } %>
                      <br>
                    <% end %>
                    <br>
                  </div>
                </div>
              </div>     
            </p>
          </div>
          
          <div class="ten wide column">
            <h4 class="ui horizontal divider header profileheader">
              <i class="mini info icon"></i>
              Persoonlijke informatie
            </h4>
            <p>
              <div class="ui grid">
                <div class="one columnn row">
                  <div class="left aligned column">
                    <p>
                      <%= h(@user.description).gsub(/\n/, '<br/>').html_safe %>
                    </p>
                  </div>
                </div>
              </div>     
            </p>
          </div>
        </div>

        <div class="three column row">
          <div class="column">
            <h4 class="ui horizontal divider header profileheader">
              <i class="mini student icon"></i>
              Cursussen
            </h4>
              <div class="ui grid">
                <% if @user.courses.any? %>
                  <div class="one column row">            
                    <div class="column">     
                    <h5 class="ui blue horizontal header profileheader">Geinteresseerd</h5>
                      <div class="ui middle aligned animated list">
                        <% @user.user_courses.each do |usercourse| %>
                        <% if usercourse.status == "Geinteresseerd"  %>  
                          <div class="item">
                            <div class="content">
                              <%= link_to(usercourse.course.name, course_path(usercourse.course), html: {class: 'header'}) %>
                            </div>
                          </div>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                  <div class="one column row">            
                    <div class="column">     
                    <h5 class="ui teal horizontal header profileheader">Ingeschreven</h5>
                      <div class="ui middle aligned animated list">
                        <% @user.user_courses.each do |usercourse| %>
                        <% if usercourse.status == "Ingeschreven"  %>  
                          <div class="item">
                            <div class="content">
                              <%= link_to(usercourse.course.name, course_path(usercourse.course), html: {class: 'header'}) %>
                            </div>
                          </div>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                  <div class="one column row">            
                    <div class="column">     
                    <h5 class="ui green horizontal header profileheader">Afgerond</h5>
                      <div class="ui middle aligned animated list">
                        <% @user.user_courses.each do |usercourse| %>
                        <% if usercourse.status == "Afgerond"  %>  
                          <div class="item">
                            <div class="content">
                              <%= link_to(usercourse.course.name, course_path(usercourse.course), html: {class: 'header'}) %>
                            </div>
                          </div>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <% else %>
                <div class="one column row">            
                  <div class="column">     
                    <div class="ui middle aligned animated list">
                    Nog geen cursussen
                    </div>
                  </div>
                </div>
                <% end %>
            </div>
          </div>
          <div class="column">
            <h4 class="ui horizontal divider header profileheader">
              <i class="mini book icon"></i>
              Kennisgebieden
            </h4>
            <div class="ui grid">
              <% if @user.skills.any? %>
                <div class="one column row">            
                  <div class="column">     
                  <h5 class="ui blue horizontal header profileheader">Beginner</h5>
                    <div class="ui middle aligned animated list">
                      <% @user.user_skills.each do |userskill| %>
                      <% if userskill.level == "Beginner"  %>  
                        <div class="item">
                          <div class="content">
                            <%= link_to(userskill.skill.name, skill_path(userskill.skill), html: {class: 'header'}) %>
                          </div>
                        </div>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="one column row">            
                  <div class="column">     
                  <h5 class="ui teal horizontal header profileheader">Gevorderd</h5>
                    <div class="ui middle aligned animated list">
                      <% @user.user_skills.each do |userskill| %>
                      <% if userskill.level == "Gevorderd"  %>  
                        <div class="item">
                          <div class="content">
                            <%= link_to(userskill.skill.name, skill_path(userskill.skill), html: {class: 'header'}) %>
                          </div>
                        </div>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="one column row">            
                  <div class="column">     
                  <h5 class="ui green horizontal header profileheader">Expert</h5>
                    <div class="ui middle aligned animated list">
                      <% @user.user_skills.each do |userskill| %>
                      <% if userskill.level == "Expert"  %>  
                        <div class="item">
                          <div class="content">
                            <%= link_to(userskill.skill.name, skill_path(userskill.skill), html: {class: 'header'}) %>
                          </div>
                        </div>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% else %>
                <div class="one column row">            
                  <div class="column">     
                    <div class="ui middle aligned animated list">
                    Nog geen kennisgebieden
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div class="column">
            <h4 class="ui horizontal divider header profileheader">
              <i class="mini users icon"></i>
              Groepen
            </h4>
            <div class="ui middle aligned animated list">
              <% if @user.groups.any? %>
                <% @user.groups.each do |group| %>
                  <div class="item">
                    <div class="content">
                      <%= link_to(group.name, group_path(group), html: {class: 'header'}) %>
                    </div>
                  </div>
                <% end %>
              <% else %>
                Nog geen groepen
              <% end %>
            </div>
          </div>
        </div> 
        
        <div class="row">
          <div class="column">
            <h4 class="ui horizontal divider header profileheader">
              <i class="mini suitcase icon"></i>
              Klanten
            </h4>
            <div class="ui list">
              
              <% if @user.clients.any? %>
                <table class="ui very basic table">
                  <thead>
                    <tr>
                      <th class="four wide">&nbsp;</th>
                      <th class="five wide">Klant</th>
                      <th class="two wide">Van</th>
                      <th class="five wide">Tot</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @user.user_clients.each do |userclient| %>
                      <tr>
                        <td class="right aligned">
                          <%= link_to Client.find_by_name(userclient.client.name) do %>
                            <img src="http://logo.clearbit.com/<%= userclient.client.logo_url %>" height="30">
                          <% end %>
                        </td>
                        <td>
                          <%= link_to Client.find_by_name(userclient.client.name) do %>
                            <%= userclient.client.name %>
                          <% end %>
                        </td>
                        <td>
                          <%= link_to Client.find_by_name(userclient.client.name) do %>
                            <%= userclient.from_date.strftime("%d/%m/%Y") %>
                          <% end %>
                        </td>
                        <td>
                          <%= link_to Client.find_by_name(userclient.client.name) do %>
                            <%= userclient.to_date.strftime("%d/%m/%Y") %>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>  
              <% else %>
                <div class="one column row">            
                  <div class="column">     
                    <div class="ui middle aligned animated list">
                    Nog geen klanten
                    </div>
                  </div>
                </div>
              <% end %>
              
            </div>
          </div>
        </div>
        
      </div>
    </div>
  </div>
</div>