config/routes.rb
Rails.application.routes.draw do

  root    'sessions#new'  
  
  get     '/home',              to: 'static_pages#home'       #home_path
  get     '/login',             to: 'sessions#new'            #login_path
  post    '/login',             to: 'sessions#create'
  delete  '/logout',            to: 'sessions#destroy'
  get     '/edit_connections',  to: 'users#edit_connections'
  
  resources :users do
    member do
      get :search
      get :edit_connections
      patch :update_connections
      put :update_connections
      get :courses
      get :groups
      get :skills
      get :clients
      end
  end
  
  resources :courses do
    member do
      get :users
    end
  end
  
  resources :groups do
    member do
      get :users
    end
  end
  
  resources :skills do
    member do
      get :users
    end
  end
  
  resources :clients do
    member do
      get :users
    end
  end
  
  resources :microposts,          only: [:create, :destroy]
  resources :user_courses,        only: [:create, :destroy]
  resources :user_groups,         only: [:create, :destroy]
  resources :user_skills,         only: [:create, :destroy]
  resources :user_clients,        only: [:create, :destroy]
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :user_skills, foreign_key: "skill_id", dependent: :destroy
  has_many :users, through: :user_skills
  
  validates :attitude, presence: true, length: { maximum: 10 }
  validates :name, presence: true, length: { maximum: 100 }, uniqueness: { case_sensitive: false }
  validates :category, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 1000 }

  # Searches in name and description
  def self.search(search)
    search = search.downcase
    wildcard_search = "%#{search}%"
    where("lower(attitude) LIKE ? OR " +
          "lower(name) LIKE ? OR " +
          "lower(category) LIKE ? OR " +
          "lower(description) LIKE ?", 
          wildcard_search, wildcard_search,
          wildcard_search, wildcard_search)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :logged_in_user,  only: [:new, :create, :show, :index, :edit, :update, :destroy]
  before_action :admin_user,      only: [:destroy]
  
  def new
    @skill = Skill.new
  end
  
  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      flash[:success] = "Nieuw kennisgebied aangemaakt!"
      redirect_to @skill
    else
      render 'new'
    end
  end
  
  def show
    @skill = Skill.find(params[:id])
  end
  
  def index
    @skills = Skill.all
    if params[:search]
      @skills = Skill.search(params[:search]).paginate(page: params[:page], per_page: 10).order("name ASC")
    else
      @skills = @skills.paginate(page: params[:page], per_page: 10).order("name ASC")
    end
  end
  
  def edit
    @skill = Skill.find(params[:id])
  end
  
  def update
    @skill = Skill.find(params[:id])
    if @skill.update_attributes(skill_params) 
      flash[:success] = "Kennisgebied succesvol bijgewerkt."
      redirect_to @skill
    else
      render 'edit'
    end
  end
  
  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy
    flash[:error] = "Kennisgebied succesvol verwijderd."
    redirect_to skills_url
  end
  
  private

    def skill_params
      params.require(:skill).permit(:attitude, :name, :category, :description)
    end
end

app/views/skills/_skill.html.erb
<!-- DESKTOP Kennisgebiedoverzichtitem -->
<div class="ui segments listoverview">
  <div class="ui segment" id="topcontainersingleitem">
    
    <%= link_to skill do %>
      <div class="<%= attitude_class(skill.attitude) %>">
        <%= skill.name %>
      </div>
    <% end %>
    
    <div class="overzichtdescription">
      <%= truncate(skill.description, :length => description_length_index_pages) %>
    </div>    
    <div class="extra">
      <div class="ui right floated labeled button" tabindex="0"> 
    
        <% if skill.users.include?(current_user) %>
          <a>
            <div class="ui red image label" id="disconnect_skill_modal_<%= skill.id %>">
              <i class="pencil icon"></i>
              Disconnect 
            </div>
          </a>
        <% else %>
          <a>
            <div class="ui green image label" id="connect_skill_modal_<%= skill.id %>">
              <i class="pencil icon"></i>
              Connect
            </div>
          </a>
        <% end %>
        
      </div>
      <a class="ui yellow image label">
        <img src="">
          <%= skill.category %>
        <div class="detail">Categorie</div>
      </a>
    </div>
  </div>
  <div class="ui bottom attached label">
    <i class="user icon"></i> <%= skill.users.count %> &nbsp; &nbsp; &nbsp;
  </div>
</div>
<!-- DESKTOP EIND Kennisgebiedoverzichtitem -->

<% if skill.users.include?(current_user) %>
<!-- DESKTOP Kennisgebiedoverzichtitem disconnect modal-->
  <div class="ui small modal" id="disconnect_skill_modal_<%= skill.id %>">
    <div class="header">
      Disconnect met kennisgebied '<%= skill.name %>'
    </div>
    
      <div class="content">
        <%= form_for(skill.user_skills.find_by(user_id: current_user.id), html: { method: :delete }) do |f| %>
          <p>Weet je het zeker?</p>
          <div class="actions">
            <div class="ui black deny button">
              Annuleren
            </div>
            <%= f.button( :class => 'ui negative right labeled icon button' ) do %>
              Disconnect <i class="remove icon"></i>
            <% end %>
          </div>
        <% end %>
      </div>
      
  </div>
<!-- DESKTOP EIND Kennisgebiedoverzichtitem disconnect modal-->
<% else %>
<!-- DESKTOP Kennisgebiedoverzichtitem connect modal-->
  <div class="ui small modal" id="connect_skill_modal_<%= skill.id %>">
    <div class="header">
      Connect met kennisgebied '<%= skill.name %>'
    </div>
    
      <div class="content">
        <%= form_for(skill.user_skills.build, html: {class: "ui form"}) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
          <%= f.hidden_field :skill_id %>
          <%= f.label :level, "Geef een indicatie van je kennis met betrekking tot dit onderwerp:"  %>
          <%= f.select(:level, ['Beginner', 'Gevorderd', 'Expert'], {prompt: default_select_value}) %><br>
          <div class="actions">
            <div class="ui black deny button">
              Annuleren
            </div>
            <%= f.button( :class => 'ui positive right labeled icon button' ) do %>
              Connect <i class="checkmark icon"></i>
            <% end %>
          </div>
        <% end %>
      </div>
      
  </div>
<!-- DESKTOP EIND Kennisgebiedoverzichtitem connect modal-->
<% end %>

<script>
  $(function() {
    $('div.label#connect_skill_modal_<%= skill.id %>').click( function(){
       $('div.modal#connect_skill_modal_<%= skill.id %>').modal('show');
    })
  })
  $(function() {
    $('div.label#disconnect_skill_modal_<%= skill.id %>').click( function(){
       $('div.modal#disconnect_skill_modal_<%= skill.id %>').modal('show');
    })
  })
</script>

app/views/skills/_skill_form.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="fields">
  <div class="six wide required field">
    <%= f.label :name, "Naam" %>
    <%= f.text_field :name %>
  </div>
  <div class="three wide required field">
    <%= f.label :attitude, "Attitude" %>
    <%= f.select(:attitude, ['Business', 'Test', 'Technical'], 
    {prompt: default_select_value}) %>
  </div>
</div>

<div class="fields">
  <div class="four wide required field">
    <%= f.label :category, "Categorie" %>
    <%= f.select(:category, ['Ontwikkellibrary','Ontwikkelmethodiek','Ontwikkeltechniek','Ontwikkeltool','Programmeertaal','Testlibrary','Testmethodiek','Testtechniek','Testtool'],
    {prompt: default_select_value}) %>
  </div>
</div>

<div class="fields">
  <div class="sixteen wide required field">
    <%= f.label :description, "Beschrijving"  %>
    <%= f.text_area :description, rows: description_rows_new_and_edit_pages %>
  </div>
</div>

app/views/skills/edit.html.erb
<% provide(:title, "Kennisgebied bewerken") %>

  <div class="ui basic segment">
          
    <div id="desktoppagetitleandsearchbar">
      <div id="titlebarsegment" class="ui basic segment">
          <h3>Kennisgebied bewerken</h3>
      </div>
    </div>
  
    <%= form_for(@skill, html: {class: "ui form"}) do |f| %>
      <%= render :partial => "skill_form", :locals => { :f => f } %>
      <%= f.submit "Sla wijzigingen op", class: "ui fluid large pink submit button" %>
    <% end %>

  </div>

app/views/skills/index.html.erb
<% provide(:title, "Kennisgebieden") %>
  
  <div id="desktoppagetitleandsearchbar">
    <div id="titlebarsegment" class="ui basic segment">
      <div class="ui basic left floated segment">
        <h3>Kennisgebieden</h3>
      </div>
      <div id="searchbarfix" class="ui basic right floated segment">
        <div class="ui icon input">
          <%= form_tag(skills_path, :method => "get") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Zoeken..." %>
          <%end%>
          <i class="search icon"></i>
        </div>
      </div>
    </div>
  </div>  

  <div class="ui basic segment">
    <div id="desktopcourseoverview">
      <% if @skills.present? %>
        <%= render @skills %>
      <% else %>
        <div class="ui basic segment">
          Geen kennisgebieden gevonden.
        </div>
      <% end %>
    <br>
    <center><%= will_paginate %></center>
  </div>

app/views/skills/new.html.erb
<% provide(:title, "Kennisgebied aanmaken") %>

  <div class="ui basic segment">
          
    <div id="desktoppagetitleandsearchbar">
      <div id="titlebarsegment" class="ui basic segment">
          <h3>Kennisgebied aanmaken</h3>
      </div>
    </div>

    <%= form_for(@skill, html: {class: "ui form"}) do |f| %>
      <%= render :partial => "skill_form", :locals => { :f => f } %>
      <%= f.submit "Maak kennisgebied aan", class: "ui fluid large pink submit button" %>
    <% end %>

  </div>

app/views/skills/show.html.erb
<% provide(:title, @skill.name) %>

<div class="ui basic segment">
  
  <div id="desktoppagetitleandsearchbar">
    <div id="titlebarsegment" class="ui basic segment">
        <h3>Kennisgebiedinformatie</h3>
    </div>
  </div>

  <div class="ui center aligned container">
    <div class="ui center aligned stacked segment">
      <div class="ui celled grid">
        
        <div class="row">
          <div class="six wide column">
            <h4 class="ui horizontal divider header profileheader">
              <i class="mini book icon"></i>
              Algemeen
            </h4>
            <p>
              <div class="ui grid">
                <div class="one columnn row">
                  <div class="left aligned column">
            <strong><%= label_tag 'name', 'Naam' %></strong>
                    <%= label_tag 'name', @skill.name%><br>
            <strong><%= label_tag 'attitude', 'Attitude' %></strong>
                    <%= label_tag 'attitude', @skill.attitude %><br>
            <strong><%= label_tag 'category', 'Categorie' %></strong>
                    <%= label_tag 'category', @skill.category %><br>
                    <br>
                    <%= link_to "Kennisgebied bewerken", edit_skill_path %><br>
                    <% if current_user.admin? %>
                    <%= link_to "Kennisgebied verwijderen", @skill, method: :delete, data: { confirm: "Weet je het zeker?" } %><br>
                    <% end %>
                    <br>
                  </div>
                </div>
              </div>     
            </p>
          </div>
          <div class="ten wide column">
            <h4 class="ui horizontal divider header profileheader">
              <i class="mini info icon"></i>
              Aanvullende informatie
            </h4>
            <p>
              <div class="ui grid">
                <div class="one columnn row">
                  <div class="left aligned column">
                    <p>
                      <%= h(@skill.description).gsub(/\n/, '<br/>').html_safe %>
                    </p>
                  </div>
                </div>
              </div>     
            </p>
          </div>
        </div>

        <div class="one column row">
          <div class="column">
            <h4 class="ui horizontal divider header profileheader">
              <i class="mini user icon"></i>
              Collega's verbonden aan dit kennisgebied
            </h4>
            
            <% if @skill.users.any? %>
            
              <div class="ui grid">
                <div class="three column row">
                  
                  <div class="column">
                    <h5 class="ui blue horizontal header profileheader">Beginner</h5>
                    <div class="ui middle aligned animated list">
                      <% @skill.user_skills.each do |userskill| %>
                      <% if userskill.level == "Beginner"  %>  
                        <div class="item">
                          <%= image_tag(user_avatar_class(userskill.user.name), {class: 'ui avatar image'}) %>
                          <div class="content">
                            <%= link_to(userskill.user.name, user_path(userskill.user), html: {class: 'header'}) %>
                          </div>
                        </div>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                  
                  <div class="column">
                    <h5 class="ui teal horizontal header profileheader">Gevorderd</h5>
                    <div class="ui middle aligned animated list">
                      <% @skill.user_skills.each do |userskill| %>
                      <% if userskill.level == "Gevorderd"  %>  
                        <div class="item">
                          <%= image_tag(user_avatar_class(userskill.user.name), {class: 'ui avatar image'}) %>
                          <div class="content">
                            <%= link_to(userskill.user.name, user_path(userskill.user), html: {class: 'header'}) %>
                          </div>
                        </div>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                  
                  <div class="column">
                    <h5 class="ui green horizontal header profileheader">Expert</h5>
                    <div class="ui middle aligned animated list">
                      <% @skill.user_skills.each do |userskill| %>
                      <% if userskill.level == "Expert"  %>  
                        <div class="item">
                          <%= image_tag(user_avatar_class(userskill.user.name), {class: 'ui avatar image'}) %>
                          <div class="content">
                            <%= link_to(userskill.user.name, user_path(userskill.user), html: {class: 'header'}) %>
                          </div>
                        </div>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                  
                </div>
              </div>
            <% else %>
              <div class="ui basic segment">
                Nog geen collega's verbonden aan dit kennisgebied.
              </div>
            <% end %>
            
            
          </div>
        </div> 
        
      </div>
    </div>
  </div>
</div>