config/routes.rb
Rails.application.routes.draw do

  root    'sessions#new'  
  
  get     '/home',              to: 'static_pages#home'       #home_path
  get     '/login',             to: 'sessions#new'            #login_path
  post    '/login',             to: 'sessions#create'
  delete  '/logout',            to: 'sessions#destroy'
  get     '/edit_connections',  to: 'users#edit_connections'
  
  resources :users do
    member do
      get :search
      get :edit_connections
      patch :update_connections
      put :update_connections
      get :courses
      get :groups
      get :skills
      get :clients
      end
  end
  
  resources :courses do
    member do
      get :users
    end
  end
  
  resources :groups do
    member do
      get :users
    end
  end
  
  resources :skills do
    member do
      get :users
    end
  end
  
  resources :clients do
    member do
      get :users
    end
  end
  
  resources :microposts,          only: [:create, :destroy]
  resources :user_courses,        only: [:create, :destroy]
  resources :user_groups,         only: [:create, :destroy]
  resources :user_skills,         only: [:create, :destroy]
  resources :user_clients,        only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<!--===============================================
	[Desktop] Navigationbar met alle dropdown mogelijkheden
===================================================-->

<div id="desktopmenu" class="ui fixed top pink menu">
  
  <a class="header item", href="<%= home_path %>">
    <%= image_tag("LogoKZAConnected.png", alt: "Home", class: "logo") %>
  </a> 
  
    <div class="ui simple dropdown item">
      <i class="user icon"></i>
      Collega's
      <i class="dropdown icon"></i>        
      <div class="menu">
        <%= link_to "Collega overzicht", users_path, class: 'item' %>
        <% if current_user.admin? %>
          <%= link_to "Collega aanmaken", new_user_path , class: 'item' %>
        <% end %>
      </div>
    </div>    

    <div class="ui simple dropdown item">
      <i class="users icon"></i>
      Groepen
      <i class="dropdown icon"></i>        
      <div class="menu">
        <%= link_to "Groep overzicht", groups_path, class: 'item' %>
        <%= link_to "Groep aanmaken", new_group_path, class: 'item' %>
      </div>
    </div>  

    <div class="ui simple dropdown item">
      <i class="student icon"></i>
      Cursussen
      <i class="dropdown icon"></i>    
      <div class="menu">
        <%= link_to "Cursus overzicht", courses_path, class: 'item' %>
        <%= link_to "Cursus aanmaken", new_course_path, class: 'item' %>
      </div>
    </div>

    <div class="ui simple dropdown item">
      <i class="book icon"></i>
      Kennisgebieden
      <i class="dropdown icon"></i>    
      <div class="menu">
        <%= link_to "Kennisgebied overzicht", skills_path, class: 'item' %>
        <%= link_to "Kennisgebied aanmaken", new_skill_path, class: 'item' %>
      </div>    
    </div>  

    <div class="ui simple dropdown item">
      <i class="suitcase icon"></i>
      Klanten
      <i class="dropdown icon"></i>    
      <div class="menu">
        <%= link_to "Klant overzicht", clients_path, class: 'item' %>
        <%= link_to "Klant aanmaken", new_client_path, class: 'item' %>
      </div>    
    </div>

    <div class="right menu">
      <div class="ui simple dropdown item">
        <i class="user icon"></i>
        <%= current_user.name %>
        <i class="dropdown icon"></i>    
        <div class="menu">
          <%= link_to "Profiel bekijken", current_user, class: 'item' %>
          <%= link_to "Profiel bewerken", edit_user_path(current_user), class: 'item' %>
          <%= link_to "Connecties bewerken", edit_connections_user_path(current_user), class: 'item' %>
        </div>    
      </div>    
    

      <a class="ui simple dropdown item" data-method="delete", href="<%= logout_path %>">
        <i class="power icon"></i>
        <div class: 'item'>Log uit</div>
      </a>
    </div>
    
  </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= full_title(yield(:title)) %>
    </title>
    
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  
  <body>
    <% if logged_in? && !current_page?(controller: 'sessions', action: 'new') && !current_page?(controller: 'sessions', action: 'destroy')  %>
      <%= render 'layouts/header' %>
    <% end %>
    
    <% if logged_in? %>
      <section class="maincontent main container">
        <div class="ui center aligned container">
            <% flash.each do |message_type, message| %>
              <br>
                <div class="<%= flash_class(message_type) %>">
                  <%= message %>
                </div>
              <br>
            <% end %>
        </div>
      <% end %>
      
      <%= yield %>
      
    </section>
    
  <script>
    setClassNameOfAllChilds("pagination","item");
    replaceClassName("field_with_errors","field error");
    replaceClassName("pagination","ui pagination menu");
  </script>

  </body>
</html>